# Resume Screening System - NLP Text Preprocessing

This notebook performs preprocessing and normalization of resume text using NLP techniques before machine learning model training.

In [2]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
      --------------------------------------- 0.0/1.6 MB 217.9 kB/s eta 0:00:07
     - -------------------------------------- 0.1/1.6 MB 297.7 kB/s eta 0:00:06
     --- ------------------------------------ 0.1/1.6 MB 607.9 kB/s eta 0:00:03
     ------ --------------------------------- 0.3/1.6 MB 923.9 kB/s eta 0:00:02
     ---------- ----------------------------- 0.4/1.6 MB 1.2 MB/s eta 0:00:01
     ------------- -------------------------- 0.5/1.6 MB 1.4 MB/s eta 0:00:01
     ---------------- ----------------------- 0.7/1.6 MB 1.6 MB/s eta 0:00:01
     ---------------------- ----------------- 0.9/1.6 MB 1.9 MB/s eta 0:00:01
     -------------------------- ------------- 1.0/1.6 MB 2.1 MB/s eta 0:00:01
     ---------------------------- ----------- 1.1/1.6 MB 2.1 MB/s eta 0:00:01
     ------------------------------ --------- 1.2/1.6 MB 2.1 MB/s eta 0:00:01
     ------------------------------ --------- 1.2/1.6 MB 2.1 MB/s eta 0:00:01
     ------------------------------ --------- 1.2/1.6 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 1.4/1.6 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 1.5/1.6 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 1.6/1.6 MB 1.9 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
     ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
     ---------------------------------------- 78.4/78.4 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: click in c:\users\akshitha\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.4.0)
Collecting regex>=2021.8.3
  Downloading regex-2026.5.9-cp310-cp310-win_amd64.whl (278 kB)
     ---------------------------------------- 0.0/278.4 kB ? eta -:--:--
     -------------------------------- ----- 235.5/278.4 kB 7.3 MB/s eta 0:00:01
     -------------------------------------  276.5/278.4 kB 3.4 MB/s eta 0:00:01
     -------------------------------------- 278.4/278.4 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: joblib in c:\users\akshitha\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: colorama in c:\users\akshitha\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.6)
Installing collected packages: tqdm, regex, nltk
Successfully installed nltk-3.9.4 regex-2026.5.9 tqdm-4.67.3

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import nltk

print("NLTK installed successfully")

NLTK installed successfully

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Akshitha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [5]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text

In [7]:
import pandas as pd

df = pd.read_csv("../data/resume_dataset.csv")

df.head()

                                              resume            category
0  Python developer with machine learning experience      Data Scientist
1            Java backend developer with spring boot   Backend Developer
2        Frontend developer with html css javascript  Frontend Developer
3           Android developer with kotlin experience    Mobile Developer
4             Data analyst with sql and excel skills        Data Analyst

In [8]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text

In [9]:
df['clean_resume'] = df['resume'].apply(clean_text)

df.head()

,resume,category,clean_resume
0,Python developer with machine learning experience,Data Scientist,python developer with machine learning experience
1,Java backend developer with spring boot,Backend Developer,java backend developer with spring boot
2,Frontend developer with html css javascript,Frontend Developer,frontend developer with html css javascript
3,Android developer with kotlin experience,Mobile Developer,android developer with kotlin experience
4,Data analyst with sql and excel skills,Data Analyst,data analyst with sql and excel skills

# Stopword Removal

Common English stopwords are removed to improve text quality for machine learning models.

In [10]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [11]:
def remove_stopwords(text):

    words = text.split()

    filtered_words = [
        word for word in words
        if word not in stop_words
    ]

    return " ".join(filtered_words)

In [12]:
df['clean_resume'] = df['clean_resume'].apply(
    remove_stopwords
)

df.head()

,resume,category,clean_resume
0,Python developer with machine learning experience,Data Scientist,python developer machine learning experience
1,Java backend developer with spring boot,Backend Developer,java backend developer spring boot
2,Frontend developer with html css javascript,Frontend Developer,frontend developer html css javascript
3,Android developer with kotlin experience,Mobile Developer,android developer kotlin experience
4,Data analyst with sql and excel skills,Data Analyst,data analyst sql excel skills

# Before vs After NLP Cleaning

In [13]:
print("ORIGINAL RESUME:\n")

print(df['resume'].iloc[0])

print("\nCLEANED RESUME:\n")

print(df['clean_resume'].iloc[0])

ORIGINAL RESUME:

Python developer with machine learning experience

CLEANED RESUME:

python developer machine learning experience